import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingBag,Heart,User,Menu,X,ArrowRight,Sun,Moon,ChevronRight,Minus,Plus,Trash2,LogOut,Star,ShieldCheck} from 'lucide-react';
import './styles.css';

const products=[
{id:1,name:'Nova Arc Jacket',category:'Outerwear',price:129,oldPrice:159,size:['S','M','L','XL'],tag:'NEW',image:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85',desc:'Structured utility outerwear with a clean architectural silhouette and soft technical finish.'},
{id:2,name:'Orbit Knit',category:'Knitwear',price:89,oldPrice:110,size:['S','M','L'],tag:'BESTSELLER',image:'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=85',desc:'A premium everyday knit designed for quiet layering and effortless movement.'},
{id:3,name:'NOVA 01 Tee',category:'Essentials',price:42,size:['S','M','L','XL'],tag:'CORE',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85',desc:'Heavyweight cotton jersey with a relaxed fit and signature NOVA detailing.'},
{id:4,name:'Aero Cargo',category:'Bottoms',price:96,size:['28','30','32','34','36'],tag:'NEW',image:'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85',desc:'Technical cargo trousers balancing utility, comfort and a sharp modern profile.'},
{id:5,name:'Flux Hoodie',category:'Essentials',price:78,size:['S','M','L','XL'],tag:'LIMITED',image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85',desc:'Dense brushed fleece hoodie with an oversized, gallery-inspired fit.'},
{id:6,name:'Vector Shirt',category:'Shirts',price:72,size:['S','M','L','XL'],tag:'CORE',image:'https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=900&q=85',desc:'Crisp everyday shirt cut with a subtle futuristic proportion.'},
{id:7,name:'Halo Sneaker',category:'Footwear',price:118,size:['7','8','9','10','11'],tag:'NEW',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',desc:'Minimal street sneaker with sculpted cushioning and all-day comfort.'},
{id:8,name:'Nova Cap',category:'Accessories',price:35,size:['ONE'],tag:'CORE',image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85',desc:'Low-profile cap finished with understated NOVA embroidery.'}
];

function App(){
 const [page,setPage]=useState('home'); const [selected,setSelected]=useState(null); const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const [dark,setDark]=useState(()=>localStorage.getItem('nove-theme')!=='light');
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('nove-user')||'null')); const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('nove-cart')||'[]')); const [wish,setWish]=useState(()=>JSON.parse(localStorage.getItem('nove-wish')||'[]')); const [toast,setToast]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('nove-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>localStorage.setItem('nove-user',JSON.stringify(user)),[user]); useEffect(()=>localStorage.setItem('nove-cart',JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem('nove-wish',JSON.stringify(wish)),[wish]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const guard=action=>{if(!user){setPage('account');notify('Sign in first to use NOVE features.');return false} return true};
 const openProduct=p=>{setSelected(p);setPage('product');window.scrollTo(0,0)};
 const addCart=(p,size='M')=>{if(!guard())return;setCart(c=>{const i=c.findIndex(x=>x.id===p.id&&x.size===size);return i>=0?c.map((x,j)=>j===i?{...x,qty:x.qty+1}:x):[...c,{...p,size,qty:1}]});notify('Added to cart');};
 const toggleWish=p=>{if(!guard())return;setWish(w=>w.includes(p.id)?w.filter(id=>id!==p.id):[...w,p.id]);notify(wish.includes(p.id)?'Removed from wishlist':'Saved to wishlist')};
 const filtered=useMemo(()=>products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(query.toLowerCase())),[query]);
 return <div className="app">
  <header className="nav"><button className="icon mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="logo" onClick={()=>setPage('home')}>NOVE<span>.</span></button>
   <nav className={menu?'navlinks open':'navlinks'}><button onClick={()=>{setPage('home');setMenu(false)}}>Home</button><button onClick={()=>{setPage('collections');setMenu(false)}}>Collections</button><button onClick={()=>{setPage('shop');setMenu(false)}}>Shop</button><button onClick={()=>{setPage('about');setMenu(false)}}>About</button></nav>
   <div className="actions"><button className="icon searchBtn" onClick={()=>guard()&&setPage('search')}><Search/></button><button className="icon" onClick={()=>guard()&&setPage('wishlist')}><Heart/>{wish.length>0&&<b>{wish.length}</b>}</button><button className="icon" onClick={()=>guard()&&setPage('cart')}><ShoppingBag/>{cart.length>0&&<b>{cart.reduce((a,x)=>a+x.qty,0)}</b>}</button><button className="icon accountIcon" onClick={()=>setPage('account')}><User/></button><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></div>
  </header>
  <main>
   {page==='home'&&<Home openProduct={openProduct} setPage={setPage}/>} 
   {page==='collections'&&<Collection openProduct={openProduct} products={products}/>} 
   {page==='shop'&&<Shop products={filtered} query={query} setQuery={setQuery} openProduct={openProduct} toggleWish={toggleWish} wish={wish}/>} 
   {page==='search'&&<Shop products={filtered} query={query} setQuery={setQuery} openProduct={openProduct} toggleWish={toggleWish} wish={wish} searchPage/>}
   {page==='product'&&selected&&<Product p={selected} addCart={addCart} toggleWish={toggleWish} wished={wish.includes(selected.id)} setPage={setPage}/>} 
   {page==='cart'&&<Cart cart={cart} setCart={setCart} setPage={setPage}/>} 
   {page==='wishlist'&&<Wishlist items={products.filter(p=>wish.includes(p.id))} openProduct={openProduct} toggleWish={toggleWish}/>} 
   {page==='account'&&<Account user={user} setUser={setUser} setPage={setPage} notify={notify}/>} 
   {page==='about'&&<About/>}
  </main>
  <Footer setPage={setPage}/>{toast&&<div className="toast">{toast}</div>}
 </div>
}

function Home({openProduct,setPage}){return <><section className="hero"><div className="heroCopy"><p className="eyebrow">NOVA / 01 — NEW SEASON</p><h1>Move<br/><em>different.</em></h1><p className="heroText">Modern essentials engineered for people who refuse to blend in. Clean forms. Quiet confidence. Zero noise.</p><button className="primary" onClick={()=>setPage('shop')}>Explore collection <ArrowRight size={18}/></button></div><div className="heroVisual"><div className="orb orb1"/><div className="orb orb2"/><div className="heroCard"><span>NOVE / SS26</span><strong>01</strong></div></div></section><section className="ticker"><span>DESIGNED FOR THE NEXT</span><span>—</span><span>BUILT TO LAST</span><span>—</span><span>LESS NOISE / MORE FORM</span></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">CURATED / 01</p><h2>New arrivals</h2></div><button className="textBtn" onClick={()=>setPage('shop')}>View all <ArrowRight size={16}/></button></div><div className="grid">{products.slice(0,4).map(p=><ProductCard key={p.id} p={p} openProduct={openProduct}/>)}</div></section><section className="manifesto"><p className="eyebrow">THE NOVA IDEA</p><h2>“The future doesn't<br/>need permission.”</h2><p>We build pieces that feel at home today and still make sense tomorrow. No disposable trends. Just considered design.</p></section></>}
function Collection({openProduct,products}){return <section className="page section"><div className="pageTitle"><p className="eyebrow">NOVE / COLLECTIONS</p><h1>Find your frequency.</h1><p>Explore the system by category.</p></div><div className="collectionGrid">{['Outerwear','Knitwear','Essentials','Bottoms','Shirts','Footwear'].map((c,i)=><div className="collection" key={c} onClick={()=>openProduct(products.find(p=>p.category===c)||products[i])}><div className="collectionImg"><img src={products[i].image}/><span>0{i+1}</span></div><div><h3>{c}</h3><ArrowRight/></div></div>)}</div></section>}
function Shop({products,query,setQuery,openProduct,toggleWish,wish,searchPage}){return <section className="page section"><div className="pageTitle"><p className="eyebrow">NOVE / {searchPage?'SEARCH':'SHOP'}</p><h1>{searchPage?'What are you looking for?':'The full system.'}</h1></div><div className="searchBar"><Search/><input autoFocus={searchPage} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, categories..."/><kbd>⌘ K</kbd></div><div className="filterRow"><span>{products.length} pieces</span><span>All products</span></div><div className="grid">{products.map(p=><ProductCard key={p.id} p={p} openProduct={openProduct} toggleWish={toggleWish} wished={wish.includes(p.id)}/>)}</div>{!products.length&&<div className="empty"><Search size={42}/><h3>No matches.</h3><p>Try a different search.</p></div>}</section>}
function ProductCard({p,openProduct,toggleWish,wished}){return <article className="card"><div className="productImg" onClick={()=>openProduct(p)}><img src={p.image}/><span className="tag">{p.tag}</span><button className="wish" onClick={e=>{e.stopPropagation();toggleWish?.(p)}}>{wished?<Heart fill="currentColor"/>:<Heart/>}</button></div><div className="productMeta"><div><p>{p.category}</p><h3 onClick={()=>openProduct(p)}>{p.name}</h3></div><strong>${p.price}</strong></div></article>}
function Product({p,addCart,toggleWish,wished,setPage}){const [size,setSize]=useState(p.size[0]);const [qty,setQty]=useState(1);return <section className="productPage section"><button className="back" onClick={()=>setPage('shop')}>← Back to shop</button><div className="productDetail"><div className="detailImage"><img src={p.image}/></div><div className="detailInfo"><p className="eyebrow">{p.category} / {p.tag}</p><h1>{p.name}</h1><div className="price">${p.price} {p.oldPrice&&<del>${p.oldPrice}</del>}</div><p className="desc">{p.desc}</p><div className="line"/><div className="label">SELECT SIZE <span>Size guide</span></div><div className="sizes">{p.size.map(s=><button className={size===s?'selected':''} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><div className="label">QUANTITY</div><div className="qty"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="primary wide" onClick={()=>{for(let i=0;i<qty;i++)addCart(p,size)}}>Add to bag <ShoppingBag size={18}/></button><button className="secondary wide" onClick={()=>toggleWish(p)}>{wished?<Heart fill="currentColor"/>:<Heart/>} {wished?'Saved to wishlist':'Add to wishlist'}</button><div className="perks"><span><ShieldCheck/> Secure checkout</span><span>↻ Easy 30-day returns</span></div></div></div></section>}
function Cart({cart,setCart,setPage}){const total=cart.reduce((a,x)=>a+x.price*x.qty,0);return <section className="page section"><div className="pageTitle"><p className="eyebrow">NOVE / BAG</p><h1>Your bag.</h1></div>{!cart.length?<div className="empty"><ShoppingBag size={42}/><h3>Your bag is empty.</h3><button className="primary" onClick={()=>setPage('shop')}>Start shopping</button></div>:<div className="cartLayout"><div>{cart.map((x,i)=><div className="cartItem" key={i}><img src={x.image}/><div className="cartData"><p>{x.category}</p><h3>{x.name}</h3><span>Size {x.size}</span><strong>${x.price}</strong><div className="miniQty"><button onClick={()=>setCart(c=>c.map((z,j)=>j===i?{...z,qty:Math.max(1,z.qty-1)}:z))}>−</button><span>{x.qty}</span><button onClick={()=>setCart(c=>c.map((z,j)=>j===i?{...z,qty:z.qty+1}:z))}>+</button></div></div><button className="delete" onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Trash2/></button></div>)}</div><aside className="summary"><p>ORDER SUMMARY</p><div><span>Subtotal</span><strong>${total.toFixed(2)}</strong></div><div><span>Shipping</span><span>Free</span></div><div className="sumTotal"><span>Total</span><strong>${total.toFixed(2)}</strong></div><button className="primary wide">Checkout <ArrowRight/></button><small>Taxes calculated at checkout.</small></aside></div>}</section>}
function Wishlist({items,openProduct,toggleWish}){return <section className="page section"><div className="pageTitle"><p className="eyebrow">NOVE / SAVED</p><h1>Wishlist.</h1></div>{!items.length?<div className="empty"><Heart size={42}/><h3>Nothing saved yet.</h3><p>Keep the pieces you love close.</p></div>:<div className="grid">{items.map(p=><ProductCard key={p.id} p={p} openProduct={openProduct} toggleWish={toggleWish} wished/>)}</div>}</section>}
function Account({user,setUser,setPage,notify}){const [form,setForm]=useState({name:'',email:'',password:''});if(user)return <section className="page section accountPage"><p className="eyebrow">NOVE / ACCOUNT</p><h1>Welcome back,<br/>{user.name}.</h1><div className="accountBox"><div><span>ACCOUNT</span><strong>{user.email}</strong></div><button className="secondary" onClick={()=>{setUser(null);notify('Signed out')}}><LogOut/> Sign out</button></div></section>;return <section className="page section accountPage"><div className="auth"><p className="eyebrow">NOVE / ACCOUNT</p><h1>Enter the<br/><em>Nova.</em></h1><p>Sign in to search, save pieces and build your bag.</p><form onSubmit={e=>{e.preventDefault();setUser({name:form.name||form.email.split('@')[0],email:form.email});notify('Welcome to NOVE')}}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@email.com"/></label><label>Password<input required type="password" minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="••••••••"/></label><button className="primary wide">Sign in <ArrowRight/></button></form></div></section>}
function About(){return <section className="page section about"><p className="eyebrow">NOVE / ABOUT</p><h1>Less, but<br/><em>better.</em></h1><div className="aboutText"><p>NOVE is a fictional independent label built around a simple idea: clothing should earn its place in your life.</p><p>We combine utility, restraint and a little bit of attitude to create a wardrobe system—not a pile of trends.</p></div></section>}
function Footer({setPage}){return <footer><div className="footerTop"><div><button className="logo" onClick={()=>setPage('home')}>NOVE<span>.</span></button><p>Modern essentials for the next version of you.</p></div><div className="footerLinks"><div><b>EXPLORE</b><button onClick={()=>setPage('shop')}>Shop</button><button onClick={()=>setPage('collections')}>Collections</button></div><div><b>HELP</b><button>Shipping</button><button>Returns</button><button>Contact</button></div><div><b>FOLLOW</b><button>Instagram</button><button>Journal</button></div></div></div><div className="footerBottom"><span>© 2026 NOVE STUDIO</span><span>MADE FOR THE NEXT.</span></div></footer>}

createRoot(document.getElementById('root')).render(<App/>);
